# Generated by Django 6.0.1 on 2026-02-01 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the course.", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the course."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        help_text="Publication status of the course.",
                        max_length=20,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Instructor who created the course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student has completed the course.",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the course was completed.",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course the student is enrolled in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="course.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student enrolled in the course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-created_at"],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the lesson.", max_length=255),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Content of the lesson (plain text)."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order index of the lesson within the course.",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this lesson belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["order", "created_at"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="Enrollment this progress belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_lessons",
                        to="course.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson that was completed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="course.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_completions",
                "ordering": ["-created_at"],
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
