"""course_id and title unique_constraint added in Lesson model

Revision ID: dd55669d5e76
Revises: 40c981c600a6
Create Date: 2026-08-22 17:59:27.202417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd55669d5e76'
down_revision: Union[str, Sequence[str], None] = '40c981c600a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_course_lesson_title', 'lessons', ['course_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_course_lesson_title', 'lessons', type_='unique')
    # ### end Alembic commands ###
