# Generated by Django 6.0.1 on 2026-02-01 05:23

import apps.authentication.models.custom_users
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Category",
                "verbose_name_plural": "Permission Categories",
            },
        ),
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
                (
                    "code_name",
                    models.CharField(
                        help_text="Code Name can have max of 50 characters",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="null=True, blank=True",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permissioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="by default=True"),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="blank=True",
                        related_name="roles",
                        to="authentication.custompermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("STUDENT", "Student"),
                            ("INSTRUCTOR", "Instructor"),
                        ],
                        default="STUDENT",
                        help_text="Enum field for the user type.",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Middle name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Email address of the user.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Profile image of the user.",
                        null=True,
                        upload_to=apps.authentication.models.custom_users.upload_path_user,
                        validators=[
                            apps.authentication.models.custom_users.validate_image
                        ],
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user account is blocked.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="authentication.custompermission"
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(blank=True, to="authentication.roles"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
